Fix issues with QLF_K6N10 cells_sim.v and dsp_sim.v
chipsalliance/yosys-f4pga-plugins pull request #378
Opened 2022-08-23 21:07 UTC by coolbreeze413

This PR has fixes for issues seen while simulating designs with the QLF_K6N10 device.

The major changes are:
- add specify blocks
- add missing signals in dsp blocks to avoid warnings
- add modules LUT_K, fpga_interconnect
- add explicit wire type declarations for inputs

2022-08-31 17:35 UTC, tpagarani commented
@mkurc-ant could someone review this PR and merge?

2022-09-01 07:59 UTC, mkurc-ant requested changes
Some minor changes requested, nothing critical. There is a conflict with the target branch that needs to be resolved.

2022-09-01 07:59 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/dsp_sim.v
> +*/
If the code is not needed it can be removed

2022-09-01 07:59 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/dsp_sim.v
> +*/
This can be removed as well.

2022-09-01 07:59 UTC, mkurc-ant commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +endmodule
You may consider moving those two models out of `cells_sim.v` Those are actually VPR specific and used only for simulation, they are not a part of the architecture.

2022-09-01 09:41 UTC, coolbreeze413 commented
@mkurc-ant I will discuss these changes and update.

2022-10-04 02:51 UTC, RandyO-QL commented on ql-qlf-plugin/qlf_k6n10f/cells_sim.v
> +endmodule
Per my discussion with Tarachand, it sounds like cells_sim.v is used by yosys, and it will also be used by the customer to run their post-layout simulation. For post-layout simulation purposes, these modules (fpga_interconnect and LUT_K) need to exist somewhere. We should consider having 2 separate files with different filenames. Perhaps a cells.v file that excludes fpga_interconnect and LUT_K, and is only used by yosys. And another file called cells_sim.v that includes all the modules needed to run a post-layout simulation (essentially it will be cells.v + fpga_interconnect + LUT_K, just as cells_sim.v is now).

2022-11-11 11:26 UTC, rakeshm75 commented
@mkurc-ant I have done the following changes:
1. Reverted the cells_sim to original version
2. Created primitives_sim.v file with post-layout macros and respective specify blocks
3. Made changes that you specified in the dsp_sim.v file

2022-11-14 08:31 UTC, mkurc-ant commented
@rakeshm75 Alright, Looks good. Could you please rebase it on top of the `main` branch? I see that there are conflicts.

2022-11-15 16:36 UTC, rakeshm75 commented
@mkurc-ant The CI issues are resolved, now you can merge.

2022-11-16 14:33 UTC, mkurc-ant approved these changes
ok, LGTM

2022-11-16 14:33 UTC, merged