systemverilog-plugin: move handle of list op to process_case_item
chipsalliance/yosys-f4pga-plugins pull request #452
Opened 2023-02-08 15:37 UTC by kamilrakoczy

Hot-fix for: https://github.com/chipsalliance/yosys-f4pga-plugins/pull/450

Ref: https://github.com/antmicro/yosys-systemverilog/issues/1448

yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4125754497/jobs/7126745238

It moves list op in set membership operator from ``process_list_op`` to ``process_case_item``.

Because ``process_list_op`` adds nodes directly to ancestor previous approach breaks processes with multiple conditions.
Ultimately I think we should refactor ``process_list_op`` to return nodes to caller instead of adding it directly as it causes a lot of confusion.

I've also added assert to ``vpiOperand`` visit in ``process_case_item`` to make sure we don't add any nodes in this visitor.

Fixing this showed that opentitan also uses identifiers as list op arguments, so I've added support for this (it was in TODO in previous PR).
Signed-off-by: Kamil Rakoczy <krakoczy@antmicro.com>

2023-02-09 12:54 UTC, mglb requested changes
Please do not use `AST::Extended` assigned to `type` in new code. This causes undefined/unexpected behaviors and makes debugging harder.
Use an attribute (new one if needed) to mark node as something special.

2023-02-09 14:31 UTC, kamilrakoczy commented
Sure, I've changed to use new attribute instead.

New yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4135116919

2023-02-13 10:50 UTC, mglb requested changes

2023-02-13 10:50 UTC, mglb commented on systemverilog-plugin/UhdmAst.cc
> +                block->children = current_node->children;
```suggestion
                block->children = std::move(current_node->children);
```

2023-02-13 10:50 UTC, mglb commented on systemverilog-plugin/UhdmAst.cc
> +            }
I believe `range_left == -1` is not an absolute indicator of invalid range. Shouldn't we check `range_valid`? Also, this ignores the range of `high`.

Also, the default should be 32:
- 32 seems to be Yosys default int constant size,
- you're storing the constant in an `int` here, so anything bigger won't work anyway,
- `mkconst_int` takes 32 bit value, so again, anything bigger won't work.

2023-02-13 11:10 UTC, kamilrakoczy commented
New yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4162797345/jobs/7202408725

2023-02-13 15:48 UTC, mglb approved these changes

2023-02-13 15:49 UTC, merged