systemverilog-plugin: handle assignment pattern with only default inside cell port
chipsalliance/yosys-f4pga-plugins pull request #460
Opened 2023-02-22 10:22 UTC by kamilrakoczy

This PR adds support for assignment patters inside cell high conn  port that is setting all values to come constant, e.g.:

```
mod  m (.data( '{default: '0} ));
```

2023-02-22 11:23 UTC, mglb requested changes
Please also add some minimal test to uhdm-integration-tests.
Such test will allow detecting regressions in this code directly. Otherwise we would need to dig through OpenTitan logs to find out what exactly failed.

2023-02-22 11:23 UTC, mglb commented on systemverilog-plugin/UhdmAst.cc
> +            if (find_ancestor({AST::AST_CELL})) {
Is it possible to add `AST::AST_CELL` to `find_ancestor` 3 lines above and reorganize the condition into something like:
```
if (!ancestor) {
    log_error(...);
}
if (ancestor->type == AST::AST_CELL) {
    ...
}
```
Reason: less nesting and one `find_ancestor` less.

2023-02-22 11:23 UTC, mglb commented on systemverilog-plugin/UhdmAst.cc
>          auto ancestor = find_ancestor({AST::AST_WIRE, AST::AST_MEMORY, AST::AST_PARAMETER, AST::AST_LOCALPARAM});
While you're there: `const auto* const`.
Same above, in `auto assign_node = ...`. This change will actually make `->clone()` you've added mandatory.

2023-02-22 11:23 UTC, mglb commented on systemverilog-plugin/UhdmAst.cc
> +                    // and we are setting all values to some constant
```suggestion
                // and we are setting all values to some constant
                if (typespec_h && vpi_get(vpiType, typespec_h) == vpiStringTypespec) {
```
For consistency with the comment + if above

2023-02-23 09:28 UTC, wsipak approved these changes

2023-02-27 10:51 UTC, kamilrakoczy commented
UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/714

yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4281547440

2023-03-23 10:54 UTC, kamilrakoczy commented
After: https://github.com/chipsalliance/Surelog/pull/3486 Surelog started to flattening such assignments, so this PR is no longer needed. Closing.

2023-03-23 10:54 UTC, closed without merging