systemverilog-plugin: fix assignments on declaration
chipsalliance/yosys-f4pga-plugins pull request #473
Opened 2023-03-27 11:24 UTC by kamilrakoczy

This PR fixes assignments on declaration in more generic way. Assignments on declaration in genfor blocks are handled separately, so they are left intact.

UHDM-integration-tests: https://github.com/chipsalliance/UHDM-integration-tests/pull/719
yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4531860494

2023-03-29 10:27 UTC, wsipak requested changes

2023-03-29 10:27 UTC, wsipak commented on systemverilog-plugin/UhdmAst.cc
> +                node->attributes.erase(UhdmAst::packed_ranges());
I think we should first `delete` the objects stored in attributes.

2023-04-03 14:47 UTC, mglb approved these changes

2023-04-03 15:08 UTC, kamilrakoczy commented
Previous yosys-systemverilog run discovered, that opentitan synthesis failed with this change. It was due to additional children in ``AST_IDENTIFIER`` that was leftover after transforming it from ``AST_WIRE``. I've fixed this.

new yosys-systemverilog run: https://github.com/antmicro/yosys-systemverilog/actions/runs/4598266847

2023-04-04 08:30 UTC, merged